server.address=127.0.0.1
server.port=8088
spring.application.name=esplus-panel
spring.thymeleaf.cache=false
spring.main.banner-mode=console
spring.output.ansi.enabled=ALWAYS
esplus.db=esplus/security.db
esplus.username=admin
esplus.password=esplus
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.springframework.boot=INFO
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=INFO
logging.level.org.apache.catalina=INFO
logging.level.org.apache.tomcat=INFO
logging.level.com.esplus=INFO
logging.charset.console=UTF-8
logging.charset.file=UTF-8
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %5p ${PID:- } --- [%15.15t] %-40.40logger{39} : %m%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} %5p ${PID:- } --- [%t] %-40.40logger{39} : %m%n
